# Generated by Django 2.0.7 on 2018-11-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicturePhoto',
            new_name='Photo',
        ),
    ]
