# Generated by Django 2.0.7 on 2018-11-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20181112_1027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PicturePhoto',
        ),
    ]
