# Generated by Django 2.0.7 on 2018-11-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_auto_20181112_1126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PicturePhoto',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
    ]
