# Generated by Django 2.0.7 on 2018-11-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0004_auto_20181112_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
    ]
