# Generated by Django 2.0.7 on 2018-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20181115_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='picture/photo/%Y/%m/%d'),
        ),
    ]
