# Generated by Django 2.0.7 on 2018-11-16 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0009_auto_20181115_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.Picture')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
