# Generated by Django 2.0.7 on 2018-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='option',
            field=models.CharField(blank=True, choices=[('f', '고정'), ('n', '일반')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='post/photo/%Y/%m/%d'),
        ),
    ]
