# Generated by Django 2.0.7 on 2018-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180924_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default=1, help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
