# Generated by Django 2.0.7 on 2018-09-25 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20180924_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='주보 날짜를 입력해주세요. 최대 100자 내외.', max_length=100, unique=True)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='post/photo/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text='공지사항 제목을 입력해주세요. 최대 100자 내외.', max_length=100, unique=True),
        ),
    ]
