# Generated by Django 2.0.7 on 2018-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180925_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, upload_to='notice/photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='weekly',
            name='photo',
            field=models.ImageField(upload_to='weekly/photo/%Y/%m/%d'),
        ),
    ]
