# Generated by Django 2.0.7 on 2018-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180925_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
