# Generated by Django 2.0.7 on 2018-10-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180925_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
