# Generated by Django 2.0.7 on 2019-02-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_group_groupcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupComment',
        ),
    ]
