# Generated by Django 2.0.7 on 2018-10-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='gallery/photo/%Y/%m/%d'),
        ),
    ]
