# Generated by Django 2.0.7 on 2018-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181003_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='hits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
