# Generated by Django 2.0.7 on 2018-10-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
