# Generated by Django 2.0.7 on 2018-11-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_weeklycomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weekly',
            options={'ordering': ['-created_at']},
        ),
    ]
